/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsLayoutRouteRouteImport } from './routes/_docsLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsLayoutTechnical_implementationRouteImport } from './routes/_docsLayout/technical_implementation'
import { Route as DocsLayoutContributingRouteImport } from './routes/_docsLayout/contributing'
import { Route as DocsLayoutContent_policyRouteImport } from './routes/_docsLayout/content_policy'
import { Route as DocsLayoutAboutRouteImport } from './routes/_docsLayout/about'

const DocsLayoutRouteRoute = DocsLayoutRouteRouteImport.update({
  id: '/_docsLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLayoutTechnical_implementationRoute =
  DocsLayoutTechnical_implementationRouteImport.update({
    id: '/technical_implementation',
    path: '/technical_implementation',
    getParentRoute: () => DocsLayoutRouteRoute,
  } as any)
const DocsLayoutContributingRoute = DocsLayoutContributingRouteImport.update({
  id: '/contributing',
  path: '/contributing',
  getParentRoute: () => DocsLayoutRouteRoute,
} as any)
const DocsLayoutContent_policyRoute =
  DocsLayoutContent_policyRouteImport.update({
    id: '/content_policy',
    path: '/content_policy',
    getParentRoute: () => DocsLayoutRouteRoute,
  } as any)
const DocsLayoutAboutRoute = DocsLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DocsLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof DocsLayoutRouteRouteWithChildren
  '/about': typeof DocsLayoutAboutRoute
  '/content_policy': typeof DocsLayoutContent_policyRoute
  '/contributing': typeof DocsLayoutContributingRoute
  '/technical_implementation': typeof DocsLayoutTechnical_implementationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof DocsLayoutRouteRouteWithChildren
  '/about': typeof DocsLayoutAboutRoute
  '/content_policy': typeof DocsLayoutContent_policyRoute
  '/contributing': typeof DocsLayoutContributingRoute
  '/technical_implementation': typeof DocsLayoutTechnical_implementationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_docsLayout': typeof DocsLayoutRouteRouteWithChildren
  '/_docsLayout/about': typeof DocsLayoutAboutRoute
  '/_docsLayout/content_policy': typeof DocsLayoutContent_policyRoute
  '/_docsLayout/contributing': typeof DocsLayoutContributingRoute
  '/_docsLayout/technical_implementation': typeof DocsLayoutTechnical_implementationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/content_policy'
    | '/contributing'
    | '/technical_implementation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/content_policy'
    | '/contributing'
    | '/technical_implementation'
  id:
    | '__root__'
    | '/'
    | '/_docsLayout'
    | '/_docsLayout/about'
    | '/_docsLayout/content_policy'
    | '/_docsLayout/contributing'
    | '/_docsLayout/technical_implementation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsLayoutRouteRoute: typeof DocsLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docsLayout': {
      id: '/_docsLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DocsLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docsLayout/about': {
      id: '/_docsLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof DocsLayoutAboutRouteImport
      parentRoute: typeof DocsLayoutRouteRoute
    }
    '/_docsLayout/content_policy': {
      id: '/_docsLayout/content_policy'
      path: '/content_policy'
      fullPath: '/content_policy'
      preLoaderRoute: typeof DocsLayoutContent_policyRouteImport
      parentRoute: typeof DocsLayoutRouteRoute
    }
    '/_docsLayout/contributing': {
      id: '/_docsLayout/contributing'
      path: '/contributing'
      fullPath: '/contributing'
      preLoaderRoute: typeof DocsLayoutContributingRouteImport
      parentRoute: typeof DocsLayoutRouteRoute
    }
    '/_docsLayout/technical_implementation': {
      id: '/_docsLayout/technical_implementation'
      path: '/technical_implementation'
      fullPath: '/technical_implementation'
      preLoaderRoute: typeof DocsLayoutTechnical_implementationRouteImport
      parentRoute: typeof DocsLayoutRouteRoute
    }
  }
}

interface DocsLayoutRouteRouteChildren {
  DocsLayoutAboutRoute: typeof DocsLayoutAboutRoute
  DocsLayoutContent_policyRoute: typeof DocsLayoutContent_policyRoute
  DocsLayoutContributingRoute: typeof DocsLayoutContributingRoute
  DocsLayoutTechnical_implementationRoute: typeof DocsLayoutTechnical_implementationRoute
}

const DocsLayoutRouteRouteChildren: DocsLayoutRouteRouteChildren = {
  DocsLayoutAboutRoute: DocsLayoutAboutRoute,
  DocsLayoutContent_policyRoute: DocsLayoutContent_policyRoute,
  DocsLayoutContributingRoute: DocsLayoutContributingRoute,
  DocsLayoutTechnical_implementationRoute:
    DocsLayoutTechnical_implementationRoute,
}

const DocsLayoutRouteRouteWithChildren = DocsLayoutRouteRoute._addFileChildren(
  DocsLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsLayoutRouteRoute: DocsLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
