# docker-compose.yml

services:
  server:
    image: ghcr.io/${GITHUB_REPOSITORY}/server:latest
    container_name: my_earth_server
    environment:
      API_SERVER_PORT: ${API_SERVER_PORT}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy

  client:
    image: ghcr.io/${GITHUB_REPOSITORY}/client:latest
    container_name: my_earth_client
    restart: unless-stopped
    ports:
      # expose port 4000 for the caddyfile
      - "4000:80"

  database:
    image: postgis/postgis:17-3.5
    container_name: my_earth_db
    environment:
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
    ports:
      # expose port 4000 for the caddyfile
      - "4000:80"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "4002:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 5s

volumes:
  postgres_data:
    driver: local

networks:
  default:
    driver: bridge
