name: Production CD

on:
  push:
    branches:
      - production

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write

    # only run if the commit came from the staging branch
    # note, if this commit message changes in staging_ci.yml, it needs to be updated here, too
    if: github.event_name == 'merge' && contains(github.event.head_commit.message, 'Merge staging into production after successful CI')
    env:
      VITE_DATABASE_ENDPOINT: ${{ secrets.VITE_DATABASE_ENDPOINT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server image
        id: build-server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push client image
        id: build-client
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./client/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/client:latest #
          build-args: VITE_DATABASE_ENDPOINT=${{ env.VITE_DATABASE_ENDPOINT }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Docker images on VPS
        run: |
          echo "[WARN] Not implemented yet."
