name: Staging CI

on:
  pull_request:
    branches:
      - staging

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: staging
    env:
      PG_PW: ${{ secrets.PG_PW }}
      PG_DB: ${{ secrets.PG_DB }}
      PG_USER: ${{ secrets.PG_USER }}
      DATABASE_URL: postgresql://${{ secrets.PG_USER }}:${{ secrets.PG_PW }}@localhost:4002/${{ secrets.PG_DB }}
      API_SERVER_PORT: ${{ secrets.API_SERVER_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Setup Docker Buildx (for DB container)
        uses: docker/setup-buildx-action@v3

      # --- Server Checks ---

      - name: Check server type errors
        run: bun run tsc
        working-directory: ./server

      - name: Start PostgreSQL container
        run: bun run db-reset
        working-directory: ./server

      - name: Run server tests
        run: bun test
        working-directory: ./server

      - name: Stop PostgreSQL container
        if: always()
        run: docker compose down -v database
        working-directory: ./server

      # --- Client Checks ---
      - name: Check client type errors
        run: bun run tsc
        working-directory: ./client

      - name: Run client tests
        run: bun test
        working-directory: ./client
